---
- name: "Directory Exists | {{ openssh_runtime_root }}"
  file:
    state: directory
    path: "{{ openssh_runtime_root }}"
    owner: root
    group: root
    mode: 0755
  tags:
    - directory-structure
    - runtime-data
    - openssh

- name: Upload Server Config | /etc/ssh/sshd_config
  template:
    src: etc/ssh/sshd_config
    dest: /etc/ssh/sshd_config
    mode: 0644
    owner: root
    group: root
  notify: Reload Service | openssh
  tags:
    - configuration
    - template-configuration
    - openssh

- name: Upload Client Config | /etc/ssh/ssh_config
  template:
    src: etc/ssh/ssh_config
    dest: /etc/ssh/ssh_config
    mode: 0644
    owner: root
    group: root
  when: openssh_client
  tags:
    - configuration
    - template-configuration
    - openssh

- name: "Upload Private Host Keys | /etc/ssh/{{ item.file }}"
  template:
    src: "{{ item.file }}"
    dest: "/{{ item.file }}"
    mode: 0600
    owner: root
    group: root
  when: "{{ item.when }}"
  notify: Reload Service | openssh
  with_items:
    - { file: etc/ssh/ssh_host_rsa_key,         when: "openssh_ssh_host[rsa] is defined" }
    - { file: etc/ssh/ssh_host_ed25519_key,     when: "openssh_ssh_host[ed25519] is defined" }
  tags:
    - openssh

- name: "Upload Public Host Keys | /etc/ssh/{{ item.file }}"
  template:
    src: "{{ item.file }}"
    dest: "/{{ item.file }}"
    mode: 0644
    owner: root
    group: root
  when: "{{ item.when }}"
  notify: Reload Service | openssh
  with_items:
    - { file: etc/ssh/ssh_host_rsa_key.pub,     when: "openssh_ssh_host[rsa] is defined" }
    - { file: etc/ssh/ssh_host_ed25519_key.pub, when: "openssh_ssh_host[ed25519] is defined" }
  tags:
    - openssh
