---
- name: "Directory Exists | {{ openssh_runtime_root }}"
  file:
    state: directory
    path: "{{ openssh_runtime_root }}"
    owner: root
    group: root
    mode: 0755
  tags:
    - directory-structure
    - runtime-data
    - openssh

- name: Upload Config | /etc/ssh/sshd_config
  template:
    src: etc/ssh/sshd_config
    dest: /etc/ssh/sshd_config
    mode: 0644
    owner: root
    group: root
  tags:
    - configuration
    - template-configuration
    - openssh

- name: "Upload Host Keys | /etc/ssh/{{ item.file }}"
  template:
    src: "{{ item.file }}"
    dest: "/{{ item.file }}"
    mode: "{{ item.mode }}"
    owner: root
    group: root
  when: "{{ item.when }}"
  notify: Reload Service | openssh
  with_items:
    - { file: etc/ssh/ssh_host_rsa_key,         mode: 0600, when: "openssh_ssh_host['rsa'][openssh_role][environment_tier]['private'] is defined" }
    - { file: etc/ssh/ssh_host_rsa_key.pub,     mode: 0600, when: "openssh_ssh_host['rsa'][openssh_role][environment_tier]['public'] is defined" }
    - { file: etc/ssh/ssh_host_ed25519_key,     mode: 0600, when: "openssh_ssh_host['ed25519'][openssh_role][environment_tier]['private'] is defined" }
    - { file: etc/ssh/ssh_host_ed25519_key.pub, mode: 0600, when: "openssh_ssh_host['ed25519'][openssh_role][environment_tier]['public'] is defined" }
  tags:
    - openssh
