---
- name: "Directory Exists | {{ openssh_runtime_root }}"
  file:
    state: directory
    path: "{{ openssh_runtime_root }}"
    owner: root
    group: root
    mode: 0755
  tags:
    - directory-structure
    - runtime-data
    - openssh

- name: Upload Config | /etc/ssh/sshd_config
  template:
    src: etc/ssh/sshd_config
    dest: /etc/ssh/sshd_config
    mode: 0644
    owner: root
    group: root
  tags:
    - configuration
    - template-configuration
    - openssh

- name: "Upload Ed25519 Private Host Keys | /etc/ssh/ssh_host_ed25519_key"
  template:
    src: "etc/ssh/ssh_host_ed25519_key"
    dest: "/etc/ssh/ssh_host_ed25519_key"
    mode: 0600
    owner: root
    group: root
  when: openssh_ssh_host_ed25519_private is defined
  tags:
    - openssh

- name: "Upload RSA Private Host Key | /etc/ssh/ssh_host_rsa_key"
  template:
    src: "etc/ssh/ssh_host_rsa_key"
    dest: "/etc/ssh/ssh_host_rsa_key"
    mode: 0600
    owner: root
    group: root
  when: openssh_ssh_host_rsa_private is defined
  tags:
    - openssh

- name: "Upload Ed25519 Public Host Keys | /etc/ssh/ssh_host_ed25519_key.pub"
  template:
    src: "etc/ssh/ssh_host_ed25519_key.pub"
    dest: "/etc/ssh/ssh_host_ed25519_key.pub"
    mode: 0644
    owner: root
    group: root
  when: openssh_ssh_host_ed25519_public is defined
  tags:
    - openssh

- name: "Upload RSA Public Host Keys | /etc/ssh/ssh_host_rsa_key.pub"
  template:
    src: "etc/ssh/ssh_host_rsa_key.pub"
    dest: "/etc/ssh/ssh_host_rsa_key.pub"
    mode: 0644
    owner: root
    group: root
  when: openssh_ssh_host_rsa_public is defined
  tags:
    - openssh
