---
- template:
    src: etc/ssh/sshd_config
    dest: /etc/ssh/sshd_config
    mode: 0644
    owner: root
    group: root
  notify: service | ssh | restart
  tags:
    - configuration
    - template-configuration
    - openssh

- name: Upload Client Config | /etc/ssh/ssh_config
  template:
    src: etc/ssh/ssh_config
    dest: /etc/ssh/ssh_config
    mode: 0644
    owner: root
    group: root
  when: openssh_client
  tags:
    - configuration
    - template-configuration
    - openssh

- name: "Upload Private Host Keys | /etc/ssh/{{ item }}"
  template:
    src: "{{ item }}"
    dest: "/{{ item }}"
    mode: 0600
    owner: root
    group: root
  when: openssh_ssh_host is defined
  notify: Reload Service | openssh
  with_items:
    - etc/ssh/ssh_host_rsa_key
    - etc/ssh/ssh_host_ed25519_key
  tags:
    - openssh

- name: "Upload Public Host Keys | /etc/ssh/{{ item }}"
  template:
    src: "{{ item }}"
    dest: "/{{ item }}"
    mode: 0644
    owner: root
    group: root
  when: openssh_ssh_host is defined
  notify: Reload Service | openssh
  with_items:
    - etc/ssh/ssh_host_rsa_key.pub
    - etc/ssh/ssh_host_ed25519_key.pub
  tags:
    - openssh

- lineinfile:
    state: present
    dest: /etc/sudoers.d/fix-ssh-agent
    regexp: '^Defaults env_keep\+\=SSH_AUTH_SOCK'
    line: 'Defaults env_keep+=SSH_AUTH_SOCK'
    create: yes
  tags:
    - configure
    - openssh
    - sudo
