---
- name: Install Packages | openssh-client
  apt:
    state: latest
    pkg: "{{ item }}"
  with_items:
    - openssh-client
  when: openssh_client

- name: Install Packages | openssh-server
  apt:
    state: latest
    pkg: "{{ item }}"
  with_items:
    - openssh-server
  when: openssh_server
