---
- name: Install Packages | openssh-client
  apt:
    state: latest
    name: "{{ item }}"
  with_items:
    - openssh-client
  when: openssh_client
  tags:
    - openssh

- name: Install Packages | openssh-server
  apt:
    state: latest
    name: "{{ item }}"
  with_items:
    - openssh-server
  when: openssh_server
  tags:
    - openssh
