---
- name: Configure | openssh | pidfile
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: '^#* *PidFile '
    line: "PidFile {{ openssh_pidfile_path }}"
  notify: Reload Service | openssh
  tags:
    - pidfile
    - service

- name: Bounce sshd to write new pidfile.
  service:
    state: restarted
    name: ssh
