---
- name: Upload Config | monit | openssh
  template:
    src: etc/monit/conf.d/openssh
    dest: /etc/monit/conf.d/openssh
  notify: Reload Service | monit
  tags:
    - monit

- name: Trigger All Callbacks
  meta: flush_handlers

- name: "Directory Exists | {{ openssh_runtime_data_root }}"
  file:
    state: directory
    path: "{{ openssh_runtime_data_root }}"
    owner: root
    group: root
    mode: 0755
  tags:
    - directory-structure
    - logging
    - openssh

- name: Configure | openssh | pidfile
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: '^#* *PidFile '
    line: "PidFile {{ openssh_pidfile_path }}"
  notify: Reload Service | openssh
  tags:
    - pidfile
    - service

- name: Confirm Monitoring | openssh
  monit:
    state: present
    name: openssh
  tags:
    - monit
