---
- name: Update Package Cache
  apt:
    update_cache: yes

- name: Reload Service | monit
  command: monit reload
  tags:
    - monit

- name: Reload Service | ssh
  monit:
    state: restarted
    name: openssh
  tags:
    - monit
